### ISSUE TITLE
SAN certificates

### ISSUE THREAD

**Issue by CPlusPlus17** [kuba/simp_le#109]
Hello

What exactly the parameters to create a SAN certificate?

Using multiple -d hosts does not work and tries to create for each host a certificate.

Thanks
Manuel

**Comment by svenk** [comment]
For me exactly `-d` works, as it is described in https://github.com/kuba/simp_le/blob/master/simp_le.py#L841 and the example in https://github.com/kuba/simp_le/blob/master/simp_le.py#L1435, that is, I can call
```
$ simple_le --default_root /path/to/my/webroot/ -d example.com -d www.example.com
```
and then get
```
$ openssl x509 -in my/certs/for/example.com/cert.pem -text
...
            X509v3 Subject Alternative Name: 
                DNS:example.com, DNS:www.example.com
```
Which is exactly what I think Subject Altnames should do.

In my configuration, those virtual hosts share the same `.well-known/acme-challenge` directory.
