### ISSUE TITLE
without privilege escalation ?

### ISSUE THREAD

**Issue by centminmod** [kuba/simp_le#11]
> Owner of ${webroot?}/.well-known/acme-challenge must be able to run the script, without privilege escalation (sudo, root, etc.)

does that mean simp_le can't be run as root user ? as my integration script/wrapper with webroot is run as root user

**Comment by kuba** [comment]
It means that the script can be run without being root user. It doesn't mean that you cannot run it as run root user - indeed you could run `simp_le` with `sudo` or `root`, but you don't have to. In fact I recommend setup which doesn't require any privilege escalation.

**Comment by centminmod** [comment]
ok cheers thanks for clarification :)
