### ISSUE TITLE
--vhost option doesn't appear to be a valid argument

### ISSUE THREAD

**Issue by mithro** [kuba/simp_le#22]
If you run the simp_le command without any arguments you get;

```
2015-12-04 02:08:30,059:ERROR:simp_le:873: You must set at least one -d/--vhost
```

`--vhost` isn't mentioned in `--help` at all and doesn't appear to be a valid command line argument, only -d seems to work?

**Comment by kuba** [comment]
Thanks for the report - fix is on its way to `master`...
