### ISSUE TITLE
Further instructions

### ISSUE THREAD

**Issue by ghost** [kuba/simp_le#24]
Some more details instructions would be great.

A couple things that aren't so clear:
- Do we just need to send request for `/.well-known/acme-challenge/*` through to the directory set in `--default_root`?
- Where and what file does this write to?
- Do you suggest installing this in `/usr/local/bin` or elsewhere?

**Comment by roweryan** [comment]
The simp_le client needs a way to let letencrypt verify you own a domain, it does that by telling the letsencrypt api that it wants a certificate for your domain, example.com. letsencrypt has to check that you control that domain, and tells the client to put a file with a specific long name under http://example.com/.well-known/acme-challenge/, once the file is there, letsencrypt tries to access it. If that succeeds, simp_le receives a certificate. Okay that's a simplification, but it's good enough.

To make the simp_le client, well, simple, it will write your certs in the current directory. You can't specify the filenames, so a good suggestion is to put them in a subdirectory which is the same as the ssl cert you are requesting. You need to tell the simp_le client which types of files you want: probably a private key (key.pem) and a a certificate with chain (fullchain.pem).

So yes you only need to allow requests for /.well-known/acme-challenge/\* through on your non-SSL vhost, and that directory needs to be writeable by whatever user you are running simp_le as, and so must the target directory for the ssl certs (i.e. the current directory)

Where to install it is up to you. Make sure you use the venv/bin version of simp_le.

**Comment by ghost** [comment]
Thank you for the explanation.

> allow requests for /.well-known/acme-challenge/\* through on your non-SSL vhost

Does it matter if port 80 redirects (301) to 443 (assuming a valid SSL cert is installed) for this endpoint? 

> Make sure you use the venv/bin version of simp_le

Where is this?

**Comment by roweryan** [comment]
> Does it matter if port 80 redirects (301) to 443 (assuming a valid SSL cert is installed) for this endpoint? 

The ACME CA server will follow redirects. See https://github.com/kuba/simp_le/issues/27#issuecomment-161974314

> Where is this?

Mine is at /opt/simp_le/venv/bin/simp_le

**Comment by ghost** [comment]
It gets built during the install process?

So your certs get generated in `/opt/simp_le/`? Do you then copy them elsewhere, or symlink them, or link your server config to that dir?

**Comment by roweryan** [comment]
Try this nice tutorial: http://blog.philippheckel.com/2015/12/04/lets-encrypt-5-min-guide-to-set-up-cronjob-based-certificate-renewal/

**Comment by ghost** [comment]
Good tutorial, thanks.

So `simp_le` creates the `/.well-known/acme-challenge/*` directory structure in the document root.

This is different to [acme-tiny](/diafygi/acme-tiny/), in which you route requests to `/.well-known/acme-challenge/*` through to a directory **you manage yourself**, which you pass to `--acme-dir`. The script controls the contents of this dir, but not the structure.

I think the latter makes more sense, as some sites are routed entirely virtually.

**Comment by roweryan** [comment]
You control the apache/nginx config, so you can map the request wherever you like. But if you have control over the documentroot, it's maybe simpler to give simp_le write access on the .well-known/acme-challenge/ sub-directory.

**Comment by ghost** [comment]
Yep cool thanks man.

Very helpful.
