### ISSUE TITLE
Exit code 1 for "renewal not necessary" and python traceback/errors.

### ISSUE THREAD

**Issue by SebastianS90** [kuba/simp_le#30]
When an error occurs like the one in #21 then python will exit with code 1.
That is bad because I'd like to distinguish "renewal not necessary" from such an unexpected error.

Can you put a try block around the complete application that catches these errors, prints a stacktrace and exits with 2?

Alternatively, you could just swap the 1 and 2 exit code meanings, but this would be a breaking change.

**Comment by kuba** [comment]
Thanks for reporting :) This should be fixed in 3c22bfa.
