### ISSUE TITLE
"E: Unable to locate package virtualenv" is confusing (although not real error)

### ISSUE THREAD

**Issue by acabal** [kuba/simp_le#35]
When running ./bootstrap.sh on Ubuntu 14.04 server LTS, it fails with this error:

> E: Unable to locate package virtualenv

This is because the virtualenv package is actually called "python-virtualenv" on 14.04.  Since this is the most recent Ubuntu LTS release it might be worth adding a check for this case so that bootstrap.sh can complete without errors.

**Comment by acabal** [comment]
A closer look at bootstrap.sh shows it already tries "python-virtualenv", and then later tries just "virtualenv".  But it looks like the error thrown by Apt isn't caught correctly in bootstrap.sh since the script still emits an error.

**Comment by kuba** [comment]
Could you please paste the entire log? `install virtualenv || true` may produce `E: Unable to locate package virtualenv`, but the `|| true` part should make sure that the script continues. In summary, check `$?` to see if the bootstrap script succeeded :)

**Comment by acabal** [comment]
Since apt-get runs for a while the complete output is quite long, but this is the relevant part at the end:

> ...
> + install virtualenv
> + apt-get install -y --no-install-recommends virtualenv
> Reading package lists... Done
> Building dependency tree  
> Reading state information... Done
> E: Unable to locate package virtualenv
> + true

So while the script exits 0, it still displays `E: Unable to locate package virtualenv`

For someone unversed in the intricacies of Python packaging (like me), a first reaction would be "Great, it says an error occurred.  Now how am I supposed to fix this?"

So an approach that would help minimize confusion might be to squelch the output of apt-get, and only output a message if an actually unrecoverable error occurred.

**Comment by kuba** [comment]
I'm glad to hear that script worked in the end. I'm a bit busy now, but patches that would hide this message (but only if it's an error), are welcome. Any takers?

**Comment by fxlv** [comment]
Just ran into same error on a Wheezy machine.
As there's no `virtualenv` package in Debian Wheezy (https://packages.debian.org/search?keywords=virtualenv&searchon=names&suite=stable&section=all) then the bootstrap script throws and error at the end.
This does not prevent the dependencies to install but still would be nicer not to have that error.
Wheezy is still considered stable for few months so maybe would be a good idea to add a conditional check to prevent installation of `virtualenv` if executed on a Wheezy machine?
