### ISSUE TITLE
Travis green despite errors

### ISSUE THREAD

**Issue by kuba** [kuba/simp_le#39]
https://travis-ci.org/kuba/simp_le/jobs/95201523

```
Global evaluation
-----------------
Your code has been rated at 9.96/10
ERROR: InvocationError: '/home/travis/build/kuba/simp_le/.tox/lint/bin/pylint --disable=locally-disabled,fixme simp_le'
___________________________________ summary ____________________________________
ERROR:   lint: commands failed
The command ". ./tests/travis.sh script" exited with 0.
Done. Your build exited with 0.
```

**Comment by kuba** [comment]
This is not specific to lint: https://travis-ci.org/kuba/simp_le/jobs/95201522:

```
----------------------------------------------------------------------
Ran 10 tests in 0.351s
FAILED (failures=1)
ERROR: InvocationError: '/home/travis/build/kuba/simp_le/.tox/py34/bin/simp_le --test'
___________________________________ summary ____________________________________
ERROR:   py34: commands failed
```

**Comment by emilyalbini** [comment]
That's because your script doesn't exit with a status code greater than zero if tox fails. Just replace `tox` with `tox || exit 1` and travis should be red.

**Comment by kuba** [comment]
The real problem was `source` + `-xe` set in shebang. This should have been fixed in:
- 70f5d3d2347e3a6cac11cd9061742caaa9e31063
- 015f2fe7dcf1e4310cb4286f4061fe492fd908e7
- 277be5352ee6996008c6423d3a51b9a698719754
