### ISSUE TITLE
Virtualenv activate is bash specfic; fix shebang of venv.sh?

### ISSUE THREAD

**Issue by e12e** [kuba/simp_le#49]
Hi,

just had a look at venv.sh, and it currently starts with: `#!/bin/sh`. That should probably be either: `#!/usr/bin/env bash`, or possibly `#!/bin/bash`. As can be seen in the top of the activate-script virtualenv generates: `# This file must be used with "source bin/activate" *from bash*`.

This means the loop at: https://github.com/kuba/simp_le/blob/master/venv.sh#L5 might not invoke the venv pip, but rather the system pip, if /bin/sh isn't bash.

If I'm not mistaken, it will _generally_ work (better) to _not_ source the activate-script, and rather call the venv-pip directly, like so: `./venv/bin/pip install -U "${pkg?}"`. That _should_ work on most shells, as far as I know.

As I've not really played with this package, I haven't prepared a pull request -- perhaps the authors are better informed than me. But I've managed to "trick" myself in a similar fashion setting up venvs from dash (default /bin/sh on Debian) before.

**Comment by kuba** [comment]
Thanks for insightful comment! I've changed to `export PATH=./venv/bin:$PATH` everywhere :)
