### ISSUE TITLE
Silent/quiet mode usable for automation

### ISSUE THREAD

**Issue by rbu** [kuba/simp_le#50]
I'd like to run automated simp_le jobs that produce zero output if they work as expected. It should report errors still.

As an example, if it's not clear what I mean, I'm thinking of the following scenarios that should produce no output:
- no persisted certificate, generation was successful
- persisted certificate, renewal not needed
- persisted certificate, needs renewal, renewal was successful

These situations, however, should be an error:
- Invalid combination of arguments
- Generation/renewal failed
- Persisted certificate could not be parsed

**Comment by kuba** [comment]
It will be very hard to accommodate your request or even infeasible, so I allow myself to close the issue for now. The way you present it suggests that you plan to use the output in some way - you realize you have exit codes for that? Also, in fact, for automation I suggest to run with the highest verbosity allowed - if there are too many logs, just rotate them on schedule.

**Comment by rbu** [comment]
I'd like to automate this using cron and it's understanding of success/failure unfortunately is "(no) output generated". I understand I could wrap it in a script that buffers all output and feeds it back to stdout based on simp_le's return code, but most unix tools have exactly that feature built in already (e.g. 'rm').

How do you suggest running on maximum verbosity yet receiving no cron email in case of success? This would be simple to set up within the application (as part of python's logging setup, which can debug log to syslog directly and only print errors to console) and much harder to achieve outside.

**Comment by kuba** [comment]
Sorry, but I really don't think this is in the scope of `simp_le`. You should rely on the fact that exit codes are well defined (moreover, in practice, all logging goes to `STDERR`, but this is not explicitly stated in the docs). For how to handle that setup in `cron` you can search the web, where you'll find e.g. https://unix.stackexchange.com/questions/57594/have-cron-email-output-to-mailto-based-on-exit-status.

**Comment by kevinoid** [comment]
I know this is closed, but I'd like to see this feature as well, for the same reasons as @rbu.  That way we don't have to reinvent our own conditional output buffering.

I'm unclear what makes this feature difficult.  Since you are already using [logging](https://docs.python.org/2/library/logging.html), wouldn't it just be a matter of having `--quiet` bump the log level to `logging.WARNING`?
