### ISSUE TITLE
Underscores are pretty uncommon for --long-args

### ISSUE THREAD

**Issue by ThiefMaster** [kuba/simp_le#52]
Most applications use dashes, i.e. `--foo-bar` instead of `--foo_bar` for multi-word argument names (argparse automatically converts them to underscores for `dest` of the argument).

Is there any specific reason for using underscores?

**Comment by kuba** [comment]
While I do understand it's uncommon to keep flags this way, this software is not like `rm`, `cd` that would be used every few minutes, but is rather meant to be put into crontab, and so I don't see it as a big usability problem. As you noted, `argparse` automatically **converts** flags to underscores, and this conversion makes grepping through code a bit harder. I find that "readability" argument good enough to keep things as they are now. Moreover, any change at this stage would unnecessarily break the CLI.
