### ISSUE TITLE
Recommended configuration for apache is now to have the full chain in the cert file

### ISSUE THREAD

**Issue by julienw** [kuba/simp_le#54]
In the "examples" page (https://github.com/kuba/simp_le/wiki/Examples) you write that for apache we need to use the 3 files with 3 different directives.

But since Apache 2.4.8 (source: http://httpd.apache.org/docs/2.4/mod/mod_ssl.html#sslcertificatefile) this is not longer recommended anymore and we can simply concatenate the full chain into the leaf certificate. March 2014 is when this was released first (in 2.4.9).

**Comment by kuba** [comment]
Note that not everyone uses latest Apache.

**Comment by julienw** [comment]
I agree; maybe it's just as easy to have a 3rd row.

Note that Debian stable uses 2.4.10 ;)

**Comment by kuba** [comment]
Third row sounds like a plan. Would you be so kind and edit the wiki, please? :)

NB Ubuntu Trusty (current LTS) is still at 2.4.7 (http://packages.ubuntu.com/trusty/apache2).

**Comment by julienw** [comment]
Just did it (I honestly didn't know I could update it !).

Tell me how this looks :)

**Comment by kuba** [comment]
It's great, thank you.
