### ISSUE TITLE
Log to syslog instead of stdout/stderr

### ISSUE THREAD

**Issue by JrCs** [kuba/simp_le#55]
Hi,

is it possible to add an option to log messages directly to syslog instead of stdout/stderr.
With that we can easily extract debug, info, warning or error messages.

**Comment by zopieux** [comment]
I would suggest using the proper mechanism of your init system. For example, using a systemd service and timer (cron-like), the program standard out streams will be appended to the journal with no additional code/config.

I'm definitely not a fan of adding this kind of specific code in _simp_le_.

**Comment by asfaltboy** [comment]
When using cron, I found logger to be invaluable for logging to syslog.

See below for an example combining it with [cron-sentry][1]:
https://gist.github.com/asfaltboy/23a7f963bbfcb48ce510307ec8cb8737

[1]: https://github.com/yipit/cron-sentry
