### ISSUE TITLE
Allow to enforce the renewal of certificates

### ISSUE THREAD

**Issue by PixelBumper** [kuba/simp_le#56]
I was wondering if it would be possible to enable forced certificate renewal in simp_le.
Some parameter like --renew maybe?

**Comment by Lekensteyn** [comment]
Try `--valid_min 8000000`. As LE certs are valid for at most 90 days, this number of seconds should be sufficient to mark certs as outdated.

**Comment by kuba** [comment]
Another way to achieve this is to simply (backup and) remove existing certificate and its key :)
