### ISSUE TITLE
--version and --help should exit with 0 instead of 2

### ISSUE THREAD

**Issue by Lekensteyn** [kuba/simp_le#59]
When an external wrapper wants to check whether the environment is sane, it can use `simp_le.py --version` or `--help` to check for sanity (whether all required Python modules are installed).

At the moment it returns 2 though. What about making it behave like the `--test` option and exit with 0 instead? These options are explicitly requested, it is not like any confusion could arise.

**Comment by kuba** [comment]
:+1: fixed in ecf4290

**Comment by Lekensteyn** [comment]
Confirmed fixed on the dev branch, let's close this issue already?

**Comment by kuba** [comment]
Issue will get closed automatically once `dev` is merged in `master`. I'm just waiting for Travis tests to finish.
