### ISSUE TITLE
Allow adding/removing domains

### ISSUE THREAD

**Issue by Baughn** [kuba/simp_le#78]
At present, simp_le requires the user to manually remove (or backup) the .pem files if the list of domains changes.

It'd be great if there was a flag that makes this just work.

An example of working around the lack of that flag: https://github.com/NixOS/nixpkgs/pull/13451

**Comment by emilyalbini** [comment]
See #36 and #62

**Comment by Baughn** [comment]
Huh. How'd I miss that?
