### ISSUE TITLE
Version dependency for acme=0.1.0

### ISSUE THREAD

**Issue by alanivey** [kuba/simp_le#81]
(I'm working on CentOS 6 and 7 RPMs and have them in a testing phase, see #69)

setup.py requires (acme=0.1.0)[https://github.com/kuba/simp_le/blob/master/setup.py#L12], not >=0.1.0. But, EPEL7 provides 0.4.0 and forcing an install of 0.1.0 with EPEL available creates some conflicts upon future upgrades of the system.

Do versions of acme 0.1.0 cause issue with simp_le, or can we use higher versions?

**Comment by kuba** [comment]
Yes, 0.1.0 is required, newer versions will not work and there are several issues in the tracker because of mixing simp_le with newer acme. Change to support 0.2.0 is not hard, I just didn't have time to push my local branch yet, sorry! :(

**Comment by alanivey** [comment]
No sweat- I had built separate RPMs for the python dependencies that were not in CentOS core or EPEL; but I'll pursue another avenue for that. I'll close this ticket and send a PR with my instructions as we discussed in #69. Thanks for the quick reply.

**Comment by kuba** [comment]
@alanthing, I've updated code to work with newer versions of ACME (only)

**Comment by alanivey** [comment]
Ok cool- apologies for not providing my RPM instructions yet. I need to remove some company-specific bits to make it a bit more generic.

**Comment by alanivey** [comment]
I submitted PR #106 for how to make a single RPM for simp_le. I had previously created RPMs for each Python dependency that was not in the default or EPEL repositories, but found it unwieldy and was needing to upgrade some vendor packages. Hopefully it helps some folks out- I've used it in production to get at least 25 certificates.
