### ISSUE TITLE
venv.sh relies on being in /path/to/simp_le already

### ISSUE THREAD

**Issue by roweryan** [kuba/simp_le#86]
`export PATH=./venv/bin:$PATH  # #49, activate script requires bash
`
You get some very weird errors if you are not in /path/to/simp_le to start with (like if you are in /path/to/certs/CERTNAME because they are written to the cwd)

**Comment by simonthum** [comment]
AFAIK you don't need to run venv.sh more than once per installation/upgrade of simp_le. I.e. when you issue certs you should not need venv.sh, and it shouldn't even be in the path. I put a symlink to the venv/bin/simp_le in my path, this works fine.

**Comment by kuba** [comment]
`export PATH=${PWD?}/venv/bin:$PATH` might be a bit better to avoid this failure scenario

Nonetheless the user is expected to update their shell configuration for persistent installation (this could be explicitly mentioned in docs).

**Comment by simonthum** [comment]
@kuba is there a known problem with the solution I use (which doesn't really involve shell config)?

**Comment by kuba** [comment]
No, symlink to `venv/bin/simp_le` is perfectly fine :)

**Comment by simonthum** [comment]
Thanks for clarifying. Awesome tool, BTW ;)

**Comment by kuba** [comment]
This should have been addressed by using `$PWD` as I noted in the other comment. See #102 for implementation.
