### ISSUE TITLE
Generated CSRs may contain a zero-length Version field

### ISSUE THREAD

**Issue by rolandshoemaker** [kuba/simp_le#94]
Since the CSR version isn't set in [`gen_csr`](https://github.com/kuba/simp_le/blob/8f258bc098a84b7a20c2732536d0740244d814f7/simp_le.py#L159) if the user is using a pre-1.0.2 version of OpenSSL the generated CSR will contain a zero-length Version field which will cause some strict parsers (e.g. the one in Golang) to fail.

Setting the version field can be done with `req.set_version(2)`.

**Comment by kuba** [comment]
Thanks, Roland :) About to push a fix.

**Comment by kuba** [comment]
Any further work on the client is stalled by https://github.com/letsencrypt/boulder/issues/1720 :(
