### ISSUE TITLE
unexpected keyword argument 'new_authzr_uri'

### ISSUE THREAD

**Issue by ryjen** [kuba/simp_le#99]
I'm using letsencrypt dokku plugin, which uses m3adow/docker-letsencrypt-simple_le, which uses this repo.  Related to https://github.com/dokku/dokku-letsencrypt/issues/50

2016-04-16 22:33:36,432:INFO:requests.packages.urllib3.connectionpool:758: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
Traceback (most recent call last):
  File "/simp_le-master/simp_le.py", line 1397, in main
    return main_with_exceptions(cli_args)
  File "/simp_le-master/simp_le.py", line 1382, in main_with_exceptions
    new_data(args, existing_data)
  File "/simp_le-master/simp_le.py", line 1283, in new_data
    for vhost in args.vhosts
  File "/simp_le-master/simp_le.py", line 1283, in <genexpr>
    for vhost in args.vhosts
TypeError: request_domain_challenges() got an unexpected keyword argument 'new_authzr_uri'

**Comment by kuba** [comment]
FTR this must have been side-effect of https://github.com/kuba/simp_le/pull/98.

I think there are two issues here:
1.  #98 constrained 0.3.0 from the bottom, but `new_authzr_uri` in `request_domain_challenges` signature is only present starting 0.5.0. I'm working on a fix.
2. Software you're using didn't update ACME library to latest version after updating the source code to latest `master`. Your immediate fix would be to upgrade manually by running `pip install -U acme` from an appropriate virtualenv. Long-term, software you're using should somehow detect changes to `setup.py` and rerun `simp_le` installation whenever `master` is upgraded. That's not something I can fix, so please file relevant bug reports against software you're using.

**Comment by kuba** [comment]
My theory is confirmed in https://travis-ci.org/kuba/simp_le/builds/123665831: `acme==0.3.0` fails with `simp_le`, though I now think `0.4.1` should be good enough (cf. https://travis-ci.org/kuba/simp_le/builds/123666527) - letsencrypt released minor version with API breaking change which is against the "versioning contract/policy"...

cc @bmw @pde
